'use strict';
/* 10代の情報室 v1.0 言語データ(日英2言語)
   window.KYUKEI_LANG = { ja, en }。全表示文字列をキー化。キー構造は両言語で完全一致。
   🔴 ja は監修済みの現行文言を一字も変えずに収録。
   🔴 en は SPEC_YC_V1_WORLD.md / SPEC_YC_V1_FILL.md の原案どおり(一字も変えない)。
   ※ データカード(onaji)と窓口(mado)は href 付きの構造データのため app.js に言語別で持つ。 */
window.KYUKEI_LANG = {

  ja: {
    appName: '10代の情報室',
    close: '× とじる',
    langTitle: 'ことば / Language',
    tab: { hitoiki:'ひといき', onaji:'データ', shitte:'しっておく', madoguchi:'まどぐち' },

    breathIn: 'すって…',
    breathOut: 'はいて…',
    onelines: [
      'ゆっくりした呼吸には、心拍を落ちつかせる はたらきがあります。',
      '深呼吸は、3回くらいでも 効果があると言われています。',
      'なにもしない時間は、脳の休息に 必要だと考えられています。',
      '休むことと さぼることは、別のものとされています。'
    ],

    onajiNote: '数字は 国の全国調査（令和2〜3年度・厚生労働省/文部科学省など）にもとづいています',

    shitte: [
      { title:'ヤングケアラーという言葉',
        body:'家族の世話や家事を日常的に担う子ども・若者を「ヤングケアラー」と呼びます。例えば、世話や家事で宿題や部活の時間がとれない。友だちの誘いを断ることが多い。夜中に家族の対応で起きる。こうした毎日がつづく状態を指します。' },
      { title:'がんばりの評価',
        body:'家事や家族の世話は、大人でも大変な仕事です。それを担う10代について、支援の現場では「すごいことをしている」と評価されています。本人ほど「たいしたことではない」と感じやすいことも、知られています。' },
      { title:'原因のとらえ方',
        body:'介護や生活の問題は、病気・お金・人手のことなど、いくつもの事情が重なって起きます。「だれかのせい」と言えるものではない、というのが支援の現場の考え方です。責める相手をさがす必要はない、ということです。' },
      { title:'相談のルール',
        body:'相談窓口には、名前を言わなくていいところがあります。話す内容も、どこまで話すかも、本人が決めてよいことになっています。ただ聞いてもらうだけの使い方ができる窓口もあります。' },
      { title:'両立という考え方',
        body:'家族を大切にすることと、自分の時間や進路を大切にすること。この2つは両立できる、というのが支援の基本的な考え方です。そのための制度やサービスも、少しずつ増えています。' },
      { title:'頼ることの位置づけ',
        body:'大人や制度に頼ることは、ずるいことでも、家族を裏切ることでもなく、本人と家族の両方を守る方法のひとつとされています。' }
    ],

    madoIntro: '相談するかどうかは、本人が決めてよいこと、とされています。ここでは、10代が使える主な窓口を紹介します。',

    memoRoomTitle: 'メモの部屋',
    memoSave: 'そっと しまう',
    memoSaved: 'しまいました',
    memoEmpty: 'まだ なにも ありません',
    close2: 'とじる',
    deleteConfirm: 'けす?',
    settings: 'せってい',

    setExitLabel: '「× とじる」で ひらく ページ',
    setExitNote: 'なにも 入れなければ Google が ひらきます',
    save: 'ほぞん',
    savedPref: 'ほぞんしました',
    setTapsLabel: 'メモを ひらく タップの 回数',
    tapUnit: '回',
    setTapsNote: '画面の いちばん上の なまえを、この 回数 だけ つづけて タップすると、メモの部屋が ひらきます',
    music: 'おんがく',
    musicOn: 'ながす',
    musicOff: 'ながさない',
    privacyNote: '記録はこの端末の中だけ。どこにも送信されません',
    credit: 'アプリ開発：介護と支援の相談どころ　そよぎ',
    version: 'バージョン 1.0',

    introOk: 'わかった',
    intro: 'この部屋には、かくれた機能があります。\nいちばん上の「{name}」の名前を {n}回 つづけてタップすると、\nメモと せっていの部屋が ひらきます。\nこの案内は、もう二度と表示されません。'
  },

  en: {
    appName: 'Teen Info Room',
    close: '× Close',
    langTitle: 'ことば / Language',
    tab: { hitoiki:'Breathe', onaji:'Data', shitte:'Basics', madoguchi:'Helplines' },

    breathIn: 'Breathe in…',
    breathOut: 'Breathe out…',
    onelines: [
      'Slow breathing is known to calm the heart rate.',
      'Even three deep breaths are said to make a difference.',
      'Time spent doing nothing is considered necessary rest for the brain.',
      'Resting and slacking off are considered two different things.'
    ],

    onajiNote: "Figures are based on Japan's national surveys (2020–2021) and on the sources noted for other countries.",

    shitte: [
      { title:'The words "young carer"',
        body:'Children and teenagers who regularly look after family members or run the household are called "young carers." For example: no time for homework or clubs because of care and chores, often turning down friends, getting up at night for a family member. When days like this continue, that is what the term means.' },
      { title:'About the effort',
        body:'Housework and caring for a family member are hard work, even for adults. Support workers describe teenagers who do this as doing something remarkable. It is also known that the young people themselves tend to feel it is "nothing special."' },
      { title:'How to think about the cause',
        body:'Care and family problems happen when many things pile up: illness, money, not enough hands. Support workers say this is not something one person can be blamed for. There is no need to look for someone to blame.' },
      { title:'How helplines work',
        body:'Some helplines do not ask for a name. What to say, and how much, is decided by the caller. Some lines simply listen.' },
      { title:'Both can matter',
        body:"Caring about family and caring about one's own time and future can go together. That is the basic idea behind youth support, and services for it are slowly growing." },
      { title:'About asking for help',
        body:'Relying on adults or on support services is not cheating, and it is not betraying the family. It is considered one way to protect both the young person and the family.' }
    ],

    madoIntro: 'Whether to talk to someone is up to each person. This page simply lists places that exist.',

    memoRoomTitle: 'The Memo Room',
    memoSave: 'Save quietly',
    memoSaved: 'Saved quietly ✓',
    memoEmpty: 'Nothing here yet.',
    close2: 'Close',
    deleteConfirm: 'Delete?',
    settings: 'Settings',

    setExitLabel: 'Page opened by "× Close"',
    setExitNote: 'If this is empty, Google opens.',
    save: 'Save',
    savedPref: 'Saved',
    setTapsLabel: 'Taps to open the Memo Room',
    tapUnit: '',
    setTapsNote: 'Tap the name at the top of the screen this many times in a row to open the Memo Room.',
    music: 'Music',
    musicOn: 'Play',
    musicOff: 'Off',
    privacyNote: 'Everything stays on this device. Nothing is ever sent anywhere.',
    credit: 'App development: SOYOGI - Care & Support Consultation',
    version: 'Version 1.0',

    introOk: 'Got it',
    intro: 'This room has a hidden feature.\nTap the name "{name}" at the top {n} times in a row\nto open the Memo Room and Settings.\nThis notice will never be shown again.'
  },

  de: {
    appName: "Teen Info Room",
    close: "× Schließen",
    langTitle: "Sprache / Language",
    tab: { hitoiki: "Atmen", onaji: "Daten", shitte: "Basiswissen", madoguchi: "Anlaufstellen" },
    breathIn: "Einatmen…",
    breathOut: "Ausatmen…",
    onelines: [
      "Langsames Atmen kann den Herzschlag beruhigen.",
      "Schon drei tiefe Atemzüge können etwas bewirken.",
      "Zeit, in der man nichts tut, gilt als notwendige Erholung für das Gehirn.",
      "Ausruhen und Faulenzen gelten als zwei verschiedene Dinge."
    ],
    onajiNote: "Die Zahlen beruhen auf Japans landesweiten Befragungen (2020-2021) und den genannten Quellen anderer Länder.",
    shitte: [
      { title: "Das Wort „Young Carer\"", body: "Kinder und Jugendliche, die regelmäßig Familienmitglieder versorgen oder den Haushalt führen, nennt man „Young Carers\". Zum Beispiel: keine Zeit für Hausaufgaben oder Hobbys wegen Pflege und Haushalt, Verabredungen oft absagen, nachts für ein Familienmitglied aufstehen. Wenn solche Tage andauern, ist genau das gemeint." },
      { title: "Über die Leistung", body: "Haushalt und die Versorgung eines Familienmitglieds sind harte Arbeit, selbst für Erwachsene. Fachleute beschreiben Jugendliche, die das leisten, als bemerkenswert. Bekannt ist auch: Die Betroffenen selbst halten es oft für „nichts Besonderes\"." },
      { title: "Wie man über die Ursache denken kann", body: "Pflege- und Familienprobleme entstehen, wenn vieles zusammenkommt: Krankheit, Geld, fehlende Hände. Fachleute sagen, dass niemand allein dafür verantwortlich gemacht werden kann. Es gibt keinen Grund, nach einem Schuldigen zu suchen." },
      { title: "Wie Anlaufstellen funktionieren", body: "Manche Anlaufstellen fragen nicht nach dem Namen. Was gesagt wird und wie viel, entscheidet die Person selbst. Manche Stellen hören auch einfach nur zu." },
      { title: "Beides kann zählen", body: "Sich um die Familie zu sorgen und sich um die eigene Zeit und Zukunft zu kümmern, kann zusammengehen. Das ist der Grundgedanke der Jugendhilfe, und entsprechende Angebote wachsen langsam." },
      { title: "Über das Um-Hilfe-Bitten", body: "Sich auf Erwachsene oder Hilfsangebote zu stützen ist kein Schummeln und kein Verrat an der Familie. Es gilt als ein Weg, die junge Person und die Familie zugleich zu schützen." }
    ],
    madoIntro: "Ob man mit jemandem spricht, entscheidet jede Person selbst. Diese Seite zeigt nur, dass es solche Orte gibt.",
    memoRoomTitle: "Das Memozimmer",
    memoSave: "Leise verwahren",
    memoSaved: "Leise verwahrt ✓",
    memoEmpty: "Noch nichts hier.",
    close2: "Schließen",
    deleteConfirm: "Löschen?",
    settings: "Einstellungen",
    setExitLabel: "Seite, die „× Schließen\" öffnet",
    setExitNote: "Bleibt dies leer, öffnet sich Google.",
    save: "Speichern",
    savedPref: "Gespeichert",
    setTapsLabel: "Tipps zum Öffnen des Memozimmers",
    tapUnit: "",
    setTapsNote: "Den Namen oben so oft hintereinander antippen, dann öffnet sich das Memozimmer.",
    music: "Musik",
    musicOn: "An",
    musicOff: "Aus",
    privacyNote: "Alles bleibt auf diesem Gerät. Nichts wird jemals irgendwohin gesendet.",
    credit: "App-Entwicklung: SOYOGI - Beratungsstelle für Pflege und Unterstützung",
    version: "Version 1.0",
    introOk: "Verstanden",
    intro: "Dieses Zimmer hat eine verborgene Funktion.\nOben den Namen „{name}\" {n} Mal hintereinander antippen,\ndann öffnen sich Memozimmer und Einstellungen.\nDieser Hinweis wird nie wieder angezeigt."
  },

  fr: {
    appName: "Teen Info Room",
    close: "× Fermer",
    langTitle: "Langue / Language",
    tab: { hitoiki: "Respirer", onaji: "Données", shitte: "Repères", madoguchi: "Contacts" },
    breathIn: "Inspire…",
    breathOut: "Expire…",
    onelines: [
      "Une respiration lente aide le cœur à se calmer.",
      "Même trois grandes respirations peuvent faire une différence.",
      "Le temps passé à ne rien faire est considéré comme un repos nécessaire pour le cerveau.",
      "Se reposer et paresser sont considérés comme deux choses différentes."
    ],
    onajiNote: "Les chiffres reposent sur les enquêtes nationales du Japon (2020-2021) et sur les sources citées pour les autres pays.",
    shitte: [
      { title: "Les mots « jeune aidant »", body: "On appelle « jeunes aidants » les enfants et adolescents qui s'occupent régulièrement d'un proche ou tiennent la maison. Par exemple : pas de temps pour les devoirs ou les loisirs à cause des soins et des tâches, des sorties souvent refusées, des réveils la nuit pour un proche. Quand ces journées se répètent, c'est de cela qu'il s'agit." },
      { title: "Sur l'effort fourni", body: "Tenir une maison et s'occuper d'un proche est un travail dur, même pour un adulte. Les professionnels de l'aide décrivent les adolescents qui le font comme accomplissant quelque chose de remarquable. On sait aussi que les intéressés eux-mêmes ont tendance à trouver cela « normal »." },
      { title: "Comment penser la cause", body: "Les difficultés de soin et de famille arrivent quand beaucoup de choses s'accumulent : la maladie, l'argent, le manque de bras. Les professionnels disent que ce n'est la faute de personne en particulier. Il n'y a pas besoin de chercher un coupable." },
      { title: "Comment fonctionnent les lignes d'écoute", body: "Certaines lignes ne demandent pas de nom. Ce qui est dit, et jusqu'où, c'est la personne qui appelle qui en décide. Certaines lignes se contentent d'écouter." },
      { title: "Les deux peuvent compter", body: "Tenir à sa famille et tenir à son propre temps et à son avenir peuvent aller ensemble. C'est l'idée de base de l'aide à la jeunesse, et les services pour cela grandissent peu à peu." },
      { title: "Sur le fait de demander de l'aide", body: "S'appuyer sur des adultes ou sur des services d'aide, ce n'est ni tricher, ni trahir sa famille. C'est considéré comme un moyen de protéger à la fois le jeune et sa famille." }
    ],
    madoIntro: "Parler ou non à quelqu'un, chacun en décide. Cette page indique simplement que ces endroits existent.",
    memoRoomTitle: "La pièce aux mémos",
    memoSave: "Ranger doucement",
    memoSaved: "Rangé doucement ✓",
    memoEmpty: "Rien ici pour l'instant.",
    close2: "Fermer",
    deleteConfirm: "Effacer ?",
    settings: "Réglages",
    setExitLabel: "Page ouverte par « × Fermer »",
    setExitNote: "Si ce champ est vide, Google s'ouvre.",
    save: "Enregistrer",
    savedPref: "Enregistré",
    setTapsLabel: "Nombre de touches pour ouvrir la pièce aux mémos",
    tapUnit: "",
    setTapsNote: "Toucher le nom en haut de l'écran ce nombre de fois d'affilée ouvre la pièce aux mémos.",
    music: "Musique",
    musicOn: "Activée",
    musicOff: "Coupée",
    privacyNote: "Tout reste sur cet appareil. Rien n'est jamais envoyé nulle part.",
    credit: "Développement de l'application : SOYOGI - Lieu de conseil en soins et soutien",
    version: "Version 1.0",
    introOk: "Compris",
    intro: "Cette pièce a une fonction cachée.\nToucher le nom « {name} » en haut {n} fois d'affilée\nouvre la pièce aux mémos et les réglages.\nCe message ne s'affichera plus jamais."
  },

  es: {
    appName: "Teen Info Room",
    close: "× Cerrar",
    langTitle: "Idioma / Language",
    tab: { hitoiki: "Respirar", onaji: "Datos", shitte: "Claves", madoguchi: "Contactos" },
    breathIn: "Inhala…",
    breathOut: "Exhala…",
    onelines: [
      "Respirar despacio ayuda a calmar el ritmo del corazón.",
      "Incluso tres respiraciones profundas pueden marcar una diferencia.",
      "El tiempo sin hacer nada se considera un descanso necesario para el cerebro.",
      "Descansar y holgazanear se consideran cosas distintas."
    ],
    onajiNote: "Las cifras se basan en las encuestas nacionales de Japón (2020-2021) y en las fuentes citadas para otros países.",
    shitte: [
      { title: "Las palabras \"joven cuidador\"", body: "A los niños y adolescentes que cuidan con regularidad de un familiar o llevan la casa se les llama \"jóvenes cuidadores\". Por ejemplo: sin tiempo para deberes o aficiones por los cuidados y las tareas, rechazar a menudo los planes con amigos, levantarse de noche por un familiar. Cuando esos días se repiten, a eso se refiere el término." },
      { title: "Sobre el esfuerzo", body: "Llevar una casa y cuidar de un familiar es un trabajo duro, incluso para una persona adulta. Los profesionales del apoyo describen a los adolescentes que lo hacen como personas que logran algo notable. También se sabe que ellos mismos tienden a sentir que \"no es nada especial\"." },
      { title: "Cómo pensar en la causa", body: "Los problemas de cuidados y de familia surgen cuando se acumulan muchas cosas: enfermedad, dinero, falta de manos. Los profesionales dicen que no es culpa de una sola persona. No hace falta buscar a quién culpar." },
      { title: "Cómo funcionan las líneas de ayuda", body: "Algunas líneas no piden el nombre. Qué contar, y hasta dónde, lo decide quien llama. Algunas líneas simplemente escuchan." },
      { title: "Las dos cosas pueden importar", body: "Querer a la familia y cuidar del propio tiempo y del propio futuro pueden ir juntos. Esa es la idea básica del apoyo a la juventud, y los servicios para ello crecen poco a poco." },
      { title: "Sobre pedir ayuda", body: "Apoyarse en personas adultas o en servicios de ayuda no es hacer trampa ni traicionar a la familia. Se considera una forma de proteger a la vez al joven y a su familia." }
    ],
    madoIntro: "Hablar o no con alguien es decisión de cada persona. Esta página solo muestra que estos lugares existen.",
    memoRoomTitle: "El cuarto de las notas",
    memoSave: "Guardar en silencio",
    memoSaved: "Guardado en silencio ✓",
    memoEmpty: "Aún no hay nada.",
    close2: "Cerrar",
    deleteConfirm: "¿Borrar?",
    settings: "Ajustes",
    setExitLabel: "Página que abre \"× Cerrar\"",
    setExitNote: "Si se deja vacío, se abre Google.",
    save: "Guardar",
    savedPref: "Guardado",
    setTapsLabel: "Toques para abrir el cuarto de las notas",
    tapUnit: "",
    setTapsNote: "Tocar el nombre de arriba este número de veces seguidas abre el cuarto de las notas.",
    music: "Música",
    musicOn: "Con música",
    musicOff: "Sin música",
    privacyNote: "Todo se queda en este dispositivo. Nunca se envía nada a ninguna parte.",
    credit: "Desarrollo de la aplicación: SOYOGI - Centro de consultas de cuidados y apoyo",
    version: "Versión 1.0",
    introOk: "Entendido",
    intro: "Este cuarto tiene una función oculta.\nTocar el nombre \"{name}\" de arriba {n} veces seguidas\nabre el cuarto de las notas y los ajustes.\nEste aviso no volverá a mostrarse nunca."
  },

  it: {
    appName: "Teen Info Room",
    close: "× Chiudi",
    langTitle: "Lingua / Language",
    tab: { hitoiki: "Respira", onaji: "Dati", shitte: "Basi", madoguchi: "Contatti" },
    breathIn: "Inspira…",
    breathOut: "Espira…",
    onelines: [
      "Respirare lentamente aiuta a calmare il battito del cuore.",
      "Anche tre respiri profondi possono fare la differenza.",
      "Il tempo passato senza fare nulla è considerato un riposo necessario per il cervello.",
      "Riposare e oziare sono considerate due cose diverse."
    ],
    onajiNote: "I numeri si basano sulle indagini nazionali del Giappone (2020-2021) e sulle fonti citate per gli altri paesi.",
    shitte: [
      { title: "Le parole \"giovane caregiver\"", body: "I bambini e i ragazzi che si prendono cura regolarmente di un familiare o mandano avanti la casa vengono chiamati \"giovani caregiver\". Per esempio: niente tempo per compiti o passioni a causa di cura e faccende, inviti degli amici rifiutati spesso, alzarsi di notte per un familiare. Quando giornate così continuano, è questo che si intende." },
      { title: "Sull'impegno", body: "Mandare avanti una casa e prendersi cura di un familiare è un lavoro duro, anche per un adulto. Chi lavora nel sostegno descrive i ragazzi che lo fanno come persone che compiono qualcosa di notevole. Si sa anche che proprio loro tendono a sentirlo come \"niente di speciale\"." },
      { title: "Come pensare alla causa", body: "I problemi di cura e di famiglia nascono quando tante cose si accumulano: malattia, soldi, mani che mancano. Chi lavora nel sostegno dice che non è colpa di una sola persona. Non serve cercare un colpevole." },
      { title: "Come funzionano le linee di ascolto", body: "Alcune linee non chiedono il nome. Cosa dire, e quanto, lo decide chi chiama. Alcune linee semplicemente ascoltano." },
      { title: "Possono contare entrambe", body: "Tenere alla famiglia e tenere al proprio tempo e al proprio futuro possono andare insieme. È l'idea di base del sostegno ai giovani, e i servizi per questo crescono poco a poco." },
      { title: "Sul chiedere aiuto", body: "Appoggiarsi agli adulti o ai servizi di aiuto non è barare, né tradire la famiglia. È considerato un modo per proteggere insieme il ragazzo e la famiglia." }
    ],
    madoIntro: "Parlare o no con qualcuno è una scelta di ognuno. Questa pagina mostra soltanto che questi luoghi esistono.",
    memoRoomTitle: "La stanza degli appunti",
    memoSave: "Riporre in silenzio",
    memoSaved: "Riposto in silenzio ✓",
    memoEmpty: "Ancora niente qui.",
    close2: "Chiudi",
    deleteConfirm: "Eliminare?",
    settings: "Impostazioni",
    setExitLabel: "Pagina aperta da \"× Chiudi\"",
    setExitNote: "Se resta vuoto, si apre Google.",
    save: "Salva",
    savedPref: "Salvato",
    setTapsLabel: "Tocchi per aprire la stanza degli appunti",
    tapUnit: "",
    setTapsNote: "Toccare il nome in alto questo numero di volte di fila apre la stanza degli appunti.",
    music: "Musica",
    musicOn: "Sì",
    musicOff: "No",
    privacyNote: "Tutto resta su questo dispositivo. Niente viene mai inviato da nessuna parte.",
    credit: "Sviluppo dell'app: SOYOGI - Sportello di consulenza per cura e sostegno",
    version: "Versione 1.0",
    introOk: "Capito",
    intro: "Questa stanza ha una funzione nascosta.\nToccare il nome \"{name}\" in alto {n} volte di fila\napre la stanza degli appunti e le impostazioni.\nQuesto avviso non verrà mai più mostrato."
  },

  pt: {
    appName: "Teen Info Room",
    close: "× Fechar",
    langTitle: "Idioma / Language",
    tab: { hitoiki: "Respirar", onaji: "Dados", shitte: "Noções", madoguchi: "Contatos" },
    breathIn: "Inspire…",
    breathOut: "Expire…",
    onelines: [
      "Respirar devagar ajuda a acalmar o ritmo do coração.",
      "Até três respirações profundas podem fazer diferença.",
      "O tempo sem fazer nada é considerado um descanso necessário para o cérebro.",
      "Descansar e vadiar são consideradas coisas diferentes."
    ],
    onajiNote: "Os números se baseiam nas pesquisas nacionais do Japão (2020-2021) e nas fontes citadas para os outros países.",
    shitte: [
      { title: "As palavras \"jovem cuidador\"", body: "Crianças e adolescentes que cuidam regularmente de um familiar ou tocam a casa são chamados de \"jovens cuidadores\". Por exemplo: sem tempo para dever de casa ou hobbies por causa dos cuidados e das tarefas, recusar muitas vezes os convites dos amigos, levantar de noite por um familiar. Quando dias assim continuam, é disso que o termo fala." },
      { title: "Sobre o esforço", body: "Tocar uma casa e cuidar de um familiar é trabalho pesado, até para adultos. Profissionais do apoio descrevem os adolescentes que fazem isso como pessoas que realizam algo notável. Também se sabe que eles mesmos tendem a achar que \"não é nada de mais\"." },
      { title: "Como pensar na causa", body: "Problemas de cuidado e de família surgem quando muitas coisas se acumulam: doença, dinheiro, falta de braços. Profissionais dizem que não é culpa de uma pessoa só. Não é preciso procurar um culpado." },
      { title: "Como funcionam as linhas de apoio", body: "Algumas linhas não pedem nome. O que contar, e até onde, é quem liga que decide. Algumas linhas simplesmente escutam." },
      { title: "As duas coisas podem importar", body: "Gostar da família e cuidar do próprio tempo e do próprio futuro podem andar juntos. Essa é a ideia básica do apoio à juventude, e os serviços para isso crescem aos poucos." },
      { title: "Sobre pedir ajuda", body: "Apoiar-se em adultos ou em serviços de ajuda não é trapaça, nem traição à família. É considerado um jeito de proteger o jovem e a família ao mesmo tempo." }
    ],
    madoIntro: "Falar ou não com alguém é decisão de cada um. Esta página apenas mostra que esses lugares existem.",
    memoRoomTitle: "O quarto das notas",
    memoSave: "Guardar em silêncio",
    memoSaved: "Guardado em silêncio ✓",
    memoEmpty: "Nada aqui ainda.",
    close2: "Fechar",
    deleteConfirm: "Apagar?",
    settings: "Configurações",
    setExitLabel: "Página aberta por \"× Fechar\"",
    setExitNote: "Se ficar vazio, abre o Google.",
    save: "Salvar",
    savedPref: "Salvo",
    setTapsLabel: "Toques para abrir o quarto das notas",
    tapUnit: "",
    setTapsNote: "Tocar o nome lá em cima esse número de vezes seguidas abre o quarto das notas.",
    music: "Música",
    musicOn: "Ligada",
    musicOff: "Desligada",
    privacyNote: "Tudo fica neste aparelho. Nada é enviado para lugar nenhum.",
    credit: "Desenvolvimento do app: SOYOGI - Centro de consultas de cuidado e apoio",
    version: "Versão 1.0",
    introOk: "Entendi",
    intro: "Este quarto tem uma função escondida.\nTocar o nome \"{name}\" lá em cima {n} vezes seguidas\nabre o quarto das notas e as configurações.\nEste aviso nunca mais será mostrado."
  },

  nl: {
    appName: "Teen Info Room",
    close: "× Sluiten",
    langTitle: "Taal / Language",
    tab: { hitoiki: "Ademen", onaji: "Cijfers", shitte: "Basis", madoguchi: "Contact" },
    breathIn: "Adem in…",
    breathOut: "Adem uit…",
    onelines: [
      "Langzaam ademen helpt het hart tot rust te komen.",
      "Zelfs drie keer diep ademhalen kan al verschil maken.",
      "Tijd waarin je niets doet, geldt als noodzakelijke rust voor de hersenen.",
      "Uitrusten en luieren worden als twee verschillende dingen gezien."
    ],
    onajiNote: "De cijfers zijn gebaseerd op de landelijke onderzoeken van Japan (2020-2021) en op de genoemde bronnen voor andere landen.",
    shitte: [
      { title: "De woorden \"jonge mantelzorger\"", body: "Kinderen en jongeren die regelmatig voor een familielid zorgen of het huishouden draaiende houden, worden \"jonge mantelzorgers\" genoemd. Bijvoorbeeld: geen tijd voor huiswerk of hobby's door zorg en taken, afspraken met vrienden vaak afzeggen, 's nachts opstaan voor een familielid. Als zulke dagen aanhouden, is dat wat de term betekent." },
      { title: "Over de inzet", body: "Een huishouden draaien en voor een familielid zorgen is zwaar werk, zelfs voor volwassenen. Hulpverleners beschrijven jongeren die dit doen als mensen die iets bijzonders presteren. Ook is bekend dat juist zij zelf vaak vinden dat het \"niets bijzonders\" is." },
      { title: "Hoe je over de oorzaak kunt denken", body: "Zorg- en gezinsproblemen ontstaan als veel dingen samenkomen: ziekte, geld, te weinig handen. Hulpverleners zeggen dat niemand daar alleen de schuld van draagt. Er hoeft geen schuldige gezocht te worden." },
      { title: "Hoe hulplijnen werken", body: "Sommige hulplijnen vragen niet naar een naam. Wat er wordt verteld, en hoeveel, bepaalt de beller zelf. Sommige lijnen luisteren alleen maar." },
      { title: "Allebei mogen tellen", body: "Om je gezin geven en om je eigen tijd en toekomst geven, kan samengaan. Dat is de basisgedachte van jeugdhulp, en de voorzieningen daarvoor groeien langzaam." },
      { title: "Over hulp vragen", body: "Steunen op volwassenen of op hulpdiensten is geen valsspelen en geen verraad aan het gezin. Het geldt als een manier om de jongere én het gezin te beschermen." }
    ],
    madoIntro: "Of je met iemand praat, beslist ieder voor zich. Deze pagina laat alleen zien dat deze plekken bestaan.",
    memoRoomTitle: "De memokamer",
    memoSave: "Stil opbergen",
    memoSaved: "Stil opgeborgen ✓",
    memoEmpty: "Nog niets hier.",
    close2: "Sluiten",
    deleteConfirm: "Wissen?",
    settings: "Instellingen",
    setExitLabel: "Pagina die \"× Sluiten\" opent",
    setExitNote: "Als dit leeg blijft, opent Google.",
    save: "Opslaan",
    savedPref: "Opgeslagen",
    setTapsLabel: "Tikken om de memokamer te openen",
    tapUnit: "",
    setTapsNote: "Tik zo vaak achter elkaar op de naam bovenaan, dan opent de memokamer.",
    music: "Muziek",
    musicOn: "Aan",
    musicOff: "Uit",
    privacyNote: "Alles blijft op dit apparaat. Er wordt nooit iets ergens naartoe gestuurd.",
    credit: "App-ontwikkeling: SOYOGI - Adviespunt voor zorg en ondersteuning",
    version: "Versie 1.0",
    introOk: "Begrepen",
    intro: "Deze kamer heeft een verborgen functie.\nTik {n} keer achter elkaar op de naam \"{name}\" bovenaan,\ndan openen de memokamer en de instellingen.\nDeze melding wordt nooit meer getoond."
  },

  sv: {
    appName: "Teen Info Room",
    close: "× Stäng",
    langTitle: "Språk / Language",
    tab: { hitoiki: "Andas", onaji: "Siffror", shitte: "Grunder", madoguchi: "Kontakter" },
    breathIn: "Andas in…",
    breathOut: "Andas ut…",
    onelines: [
      "Långsam andning hjälper hjärtat att lugna sig.",
      "Redan tre djupa andetag kan göra skillnad.",
      "Tid då man inte gör någonting räknas som nödvändig vila för hjärnan.",
      "Att vila och att lata sig räknas som två olika saker."
    ],
    onajiNote: "Siffrorna bygger på Japans nationella undersökningar (2020-2021) och på angivna källor för andra länder.",
    shitte: [
      { title: "Orden \"ung omsorgsgivare\"", body: "Barn och unga som regelbundet tar hand om en familjemedlem eller sköter hemmet kallas \"unga omsorgsgivare\". Till exempel: ingen tid för läxor eller fritid på grund av omsorg och sysslor, ofta tacka nej till kompisar, gå upp på natten för en familjemedlem. När sådana dagar fortsätter är det just det ordet betyder." },
      { title: "Om insatsen", body: "Att sköta ett hem och ta hand om en familjemedlem är hårt arbete, även för vuxna. De som arbetar med stöd beskriver unga som gör detta som personer som gör något anmärkningsvärt. Det är också känt att de själva ofta tycker att det \"inte är något särskilt\"." },
      { title: "Hur man kan tänka kring orsaken", body: "Omsorgs- och familjeproblem uppstår när mycket hopar sig: sjukdom, pengar, för få händer. De som arbetar med stöd säger att ingen ensam kan lastas för det. Man behöver inte leta efter någon att skylla på." },
      { title: "Hur stödlinjer fungerar", body: "Vissa stödlinjer frågar inte efter namn. Vad som sägs, och hur mycket, bestämmer den som hör av sig. Vissa linjer bara lyssnar." },
      { title: "Båda kan få räknas", body: "Att bry sig om sin familj och att bry sig om sin egen tid och framtid kan gå ihop. Det är grundtanken i stödet till unga, och tjänsterna för det växer sakta." },
      { title: "Om att be om hjälp", body: "Att luta sig mot vuxna eller mot stödtjänster är inte att fuska, och inte att svika familjen. Det räknas som ett sätt att skydda både den unga och familjen." }
    ],
    madoIntro: "Om man vill prata med någon avgör var och en själv. Den här sidan visar bara att sådana platser finns.",
    memoRoomTitle: "Anteckningsrummet",
    memoSave: "Lägg undan tyst",
    memoSaved: "Undanlagt tyst ✓",
    memoEmpty: "Inget här ännu.",
    close2: "Stäng",
    deleteConfirm: "Radera?",
    settings: "Inställningar",
    setExitLabel: "Sida som \"× Stäng\" öppnar",
    setExitNote: "Om detta lämnas tomt öppnas Google.",
    save: "Spara",
    savedPref: "Sparat",
    setTapsLabel: "Tryck för att öppna anteckningsrummet",
    tapUnit: "",
    setTapsNote: "Tryck på namnet högst upp så här många gånger i rad, så öppnas anteckningsrummet.",
    music: "Musik",
    musicOn: "På",
    musicOff: "Av",
    privacyNote: "Allt stannar på den här enheten. Ingenting skickas någonsin någonstans.",
    credit: "Apputveckling: SOYOGI - Rådgivning för omsorg och stöd",
    version: "Version 1.0",
    introOk: "Förstått",
    intro: "Det här rummet har en dold funktion.\nTryck på namnet \"{name}\" högst upp {n} gånger i rad,\nså öppnas anteckningsrummet och inställningarna.\nDet här meddelandet visas aldrig igen."
  },

  ko: {
    appName: "Teen Info Room",
    close: "× 닫기",
    langTitle: "언어 / Language",
    tab: { hitoiki: "숨쉬기", onaji: "데이터", shitte: "알아두기", madoguchi: "창구" },
    breathIn: "들이쉬고…",
    breathOut: "내쉬고…",
    onelines: [
      "천천히 숨을 쉬면 심장 박동이 차분해지는 것으로 알려져 있습니다.",
      "깊은 숨 세 번만으로도 달라진다고 합니다.",
      "아무것도 하지 않는 시간은 뇌에 필요한 휴식으로 여겨집니다.",
      "쉬는 것과 게으름은 서로 다른 것으로 여겨집니다."
    ],
    onajiNote: "숫자는 일본의 전국 조사(2020-2021)와 각 나라별로 표기된 출처에 근거합니다.",
    shitte: [
      { title: "'영 케어러'라는 말", body: "가족을 돌보거나 집안일을 도맡아 하는 어린이·청소년을 '영 케어러'라고 부릅니다. 예를 들어 돌봄과 집안일 때문에 숙제나 동아리 시간이 없다, 친구의 제안을 자주 거절한다, 밤중에 가족 때문에 일어난다. 이런 날들이 계속되는 상태를 가리키는 말입니다." },
      { title: "노력에 대한 평가", body: "집안일과 가족 돌봄은 어른에게도 힘든 일입니다. 이를 해내는 10대에 대해 지원 현장에서는 \"대단한 일을 하고 있다\"고 평가합니다. 정작 본인일수록 \"별것 아니다\"라고 느끼기 쉽다는 것도 알려져 있습니다." },
      { title: "원인을 바라보는 방법", body: "돌봄과 가족의 문제는 병, 돈, 일손 부족 등 여러 사정이 겹쳐서 일어납니다. 누구 한 사람의 탓이라고 할 수 없다는 것이 지원 현장의 생각입니다. 탓할 사람을 찾을 필요는 없다는 뜻입니다." },
      { title: "상담 창구의 규칙", body: "이름을 말하지 않아도 되는 창구가 있습니다. 무엇을 어디까지 이야기할지는 거는 사람이 정합니다. 그냥 들어주기만 하는 창구도 있습니다." },
      { title: "둘 다 소중히 해도 된다", body: "가족을 소중히 하는 것과 자신의 시간과 미래를 소중히 하는 것은 함께할 수 있다는 것이 청소년 지원의 기본 생각입니다. 이를 위한 제도와 서비스도 조금씩 늘고 있습니다." },
      { title: "기대는 것의 의미", body: "어른이나 지원 제도에 기대는 것은 반칙도, 가족을 배신하는 것도 아닙니다. 본인과 가족을 함께 지키는 방법의 하나로 여겨집니다." }
    ],
    madoIntro: "이야기할지 말지는 본인이 정해도 되는 일입니다. 이 페이지는 그런 곳이 있다는 안내일 뿐입니다.",
    memoRoomTitle: "메모의 방",
    memoSave: "조용히 넣어두기",
    memoSaved: "조용히 넣어두었습니다 ✓",
    memoEmpty: "아직 아무것도 없습니다.",
    close2: "닫기",
    deleteConfirm: "지울까요?",
    settings: "설정",
    setExitLabel: "\"× 닫기\"로 열리는 페이지",
    setExitNote: "비워 두면 Google이 열립니다.",
    save: "저장",
    savedPref: "저장했습니다",
    setTapsLabel: "메모의 방을 여는 탭 횟수",
    tapUnit: "",
    setTapsNote: "화면 맨 위의 이름을 이 횟수만큼 연달아 탭하면 메모의 방이 열립니다.",
    music: "음악",
    musicOn: "켜기",
    musicOff: "끄기",
    privacyNote: "기록은 이 기기 안에만 있습니다. 어디에도 전송되지 않습니다.",
    credit: "앱 개발: SOYOGI - 돌봄과 지원 상담소",
    version: "버전 1.0",
    introOk: "알겠어요",
    intro: "이 방에는 숨겨진 기능이 있습니다.\n맨 위의 \"{name}\" 이름을 {n}번 연달아 탭하면\n메모의 방과 설정이 열립니다.\n이 안내는 두 번 다시 표시되지 않습니다."
  },

  zh: {
    appName: "Teen Info Room",
    close: "× 关闭",
    langTitle: "语言 / Language",
    tab: { hitoiki: "呼吸", onaji: "数据", shitte: "常识", madoguchi: "窗口" },
    breathIn: "吸气…",
    breathOut: "呼气…",
    onelines: [
      "缓慢的呼吸有助于让心跳平静下来。",
      "据说哪怕三次深呼吸也会有帮助。",
      "什么都不做的时间,被认为是大脑必需的休息。",
      "休息和偷懒,被认为是两回事。"
    ],
    onajiNote: "数字基于日本的全国调查(2020-2021)以及各国注明的出处。",
    shitte: [
      { title: "\"年轻照顾者\"这个词", body: "经常照顾家人或操持家务的儿童和青少年,被称为\"年轻照顾者\"。例如:因为照顾和家务没有时间做作业或参加社团;经常拒绝朋友的邀请;半夜为家人起床。当这样的日子持续下去,就是这个词所指的状态。" },
      { title: "关于付出的评价", body: "家务和照顾家人,即使对大人来说也是辛苦的工作。对于承担这些的青少年,支援一线的评价是\"在做了不起的事\"。同时也众所周知,越是本人越容易觉得\"没什么大不了\"。" },
      { title: "如何看待原因", body: "照顾和家庭的问题,是疾病、金钱、人手不足等多种情况叠加造成的。支援一线认为,这不能归咎于某一个人。也就是说,不需要去寻找该责怪的人。" },
      { title: "咨询窗口的规则", body: "有些窗口不需要说出名字。说什么、说到哪里,都由打电话的人自己决定。也有只是倾听的窗口。" },
      { title: "两者可以兼顾", body: "珍惜家人和珍惜自己的时间与未来,这两件事可以并存。这是青少年支援的基本理念,相关的制度和服务也在慢慢增加。" },
      { title: "关于寻求帮助", body: "依靠大人或支援服务,既不是耍赖,也不是背叛家人。它被认为是同时保护本人和家人的方法之一。" }
    ],
    madoIntro: "要不要和别人谈,由本人决定。这个页面只是告诉你,这样的地方是存在的。",
    memoRoomTitle: "便签的房间",
    memoSave: "悄悄收起来",
    memoSaved: "悄悄收起来了 ✓",
    memoEmpty: "这里还什么都没有。",
    close2: "关闭",
    deleteConfirm: "删除?",
    settings: "设置",
    setExitLabel: "\"× 关闭\"打开的页面",
    setExitNote: "留空则打开 Google。",
    save: "保存",
    savedPref: "已保存",
    setTapsLabel: "打开便签房间的点按次数",
    tapUnit: "",
    setTapsNote: "连续点按屏幕最上方的名字这个次数,便签的房间就会打开。",
    music: "音乐",
    musicOn: "开",
    musicOff: "关",
    privacyNote: "记录只保存在这台设备里,不会发送到任何地方。",
    credit: "应用开发: SOYOGI - 照护与支援咨询处",
    version: "版本 1.0",
    introOk: "知道了",
    intro: "这个房间有一个隐藏功能。\n连续点按最上方的名字\"{name}\" {n}次,\n便签的房间和设置就会打开。\n这条提示不会再次显示。"
  },

  ar: {
    appName: "Teen Info Room",
    close: "× إغلاق",
    langTitle: "اللغة / Language",
    tab: { hitoiki: "تنفّس", onaji: "أرقام", shitte: "أساسيات", madoguchi: "جهات" },
    breathIn: "شهيق…",
    breathOut: "زفير…",
    onelines: [
      "التنفّس البطيء يساعد على تهدئة ضربات القلب.",
      "حتى ثلاثة أنفاس عميقة يمكن أن تُحدث فرقًا.",
      "الوقت الذي لا نفعل فيه شيئًا يُعتبر راحة ضرورية للدماغ.",
      "الراحة والكسل يُعتبران شيئين مختلفين."
    ],
    onajiNote: "تستند الأرقام إلى المسوح الوطنية اليابانية (2020-2021) وإلى المصادر المذكورة للبلدان الأخرى.",
    shitte: [
      { title: "كلمة «مقدم رعاية يافع»", body: "يُطلق اسم «مقدمي الرعاية اليافعين» على الأطفال والمراهقين الذين يعتنون بانتظام بأحد أفراد الأسرة أو يديرون شؤون البيت. مثلًا: لا وقت للواجبات أو الهوايات بسبب الرعاية والأعمال المنزلية، ورفض دعوات الأصدقاء كثيرًا، والاستيقاظ ليلًا من أجل أحد أفراد الأسرة. حين تستمر أيام كهذه، فهذا ما تعنيه الكلمة." },
      { title: "عن تقدير الجهد", body: "الأعمال المنزلية ورعاية أحد أفراد الأسرة عمل شاق حتى على الكبار. والعاملون في مجال الدعم يصفون اليافعين الذين يقومون بذلك بأنهم يفعلون شيئًا رائعًا. ومن المعروف أيضًا أن أصحاب الشأن أنفسهم يميلون إلى الشعور بأنه «شيء عادي»." },
      { title: "كيف ننظر إلى السبب", body: "مشكلات الرعاية والأسرة تحدث حين تتراكم أمور كثيرة: المرض، والمال، وقلة الأيدي. ويقول العاملون في الدعم إنه لا يمكن تحميل شخص واحد المسؤولية. أي لا حاجة للبحث عن أحد نلومه." },
      { title: "قواعد جهات الاستماع", body: "بعض الجهات لا تسأل عن الاسم. وما يُقال ومقداره يقرره المتصل بنفسه. وبعض الخطوط تكتفي بالاستماع." },
      { title: "يمكن أن يهمّ الاثنان معًا", body: "الاهتمام بالأسرة والاهتمام بوقتك ومستقبلك يمكن أن يجتمعا. هذه هي الفكرة الأساسية في دعم اليافعين، والخدمات لذلك تنمو شيئًا فشيئًا." },
      { title: "عن طلب المساعدة", body: "الاستناد إلى الكبار أو إلى خدمات الدعم ليس غشًا ولا خيانة للأسرة. بل يُعتبر وسيلة لحماية اليافع والأسرة معًا." }
    ],
    madoIntro: "التحدث مع أحد أو عدمه قرار يعود لكل شخص. هذه الصفحة تخبر فقط بأن هذه الأماكن موجودة.",
    memoRoomTitle: "غرفة المذكرات",
    memoSave: "احفظ بهدوء",
    memoSaved: "حُفظ بهدوء ✓",
    memoEmpty: "لا شيء هنا بعد.",
    close2: "إغلاق",
    deleteConfirm: "حذف؟",
    settings: "الإعدادات",
    setExitLabel: "الصفحة التي يفتحها «× إغلاق»",
    setExitNote: "إذا تُرك فارغًا يُفتح Google.",
    save: "حفظ",
    savedPref: "تم الحفظ",
    setTapsLabel: "عدد النقرات لفتح غرفة المذكرات",
    tapUnit: "",
    setTapsNote: "انقر على الاسم في أعلى الشاشة هذا العدد من المرات متتاليةً فتُفتح غرفة المذكرات.",
    music: "الموسيقى",
    musicOn: "تشغيل",
    musicOff: "إيقاف",
    privacyNote: "كل شيء يبقى على هذا الجهاز. لا يُرسل أي شيء إلى أي مكان أبدًا.",
    credit: "تطوير التطبيق: SOYOGI - مركز استشارات الرعاية والدعم",
    version: "الإصدار 1.0",
    introOk: "فهمت",
    intro: "لهذه الغرفة خاصية مخفية.\nانقر على الاسم «{name}» في الأعلى {n} مرات متتالية\nفتُفتح غرفة المذكرات والإعدادات.\nلن يظهر هذا التنبيه مرة أخرى أبدًا."
  }

};
